# -*- coding: utf-8 -*-
"""within-sub_visualisations.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HrAxUCA4dUd4u8gLVFqBDwW5B0EikoLC

# **VISUALIZATIONS METHODOLOGY**

1. Metric Summary: Accuracy and AUC
This grouped bar chart visualizes the mean Classification Accuracy and the Area Under the Receiver Operating Characteristic Curve (AUC-ROC) for each model. Error bars represent the standard deviation ($\pm 1$ SD) across $k$-fold cross-validation, satisfying the requirement to report point estimates with corresponding variance metrics. Empirical $p$-values derived from permutation testing ($n=1000$) are annotated to establish the statistical significance of the decoding performance against chance levels.  

2. Normalized Confusion Matrices
Confusion matrices are computed for each model and normalized by the true class support. This visualization explicitly displays the True Positive Rate (Sensitivity) on the valid syntax class and True Negative Rate (Specificity) on the invalid syntax class. Reporting these metrics is mandated for rigorous biomedical predictive modeling to evaluate potential biases toward the majority class.  

3. Receiver Operating Characteristic (ROC) Curves
The ROC curve plots the True Positive Rate against the False Positive Rate across varying decision thresholds. For $k$-fold cross-validation, the mean ROC curve is plotted alongside a shaded region representing $\pm 1$ standard deviation. This illustrates the variance in decision boundaries and provides a comprehensive view of model stability
"""

import os
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.metrics import roc_curve, auc, confusion_matrix, accuracy_score
from google.colab import drive

plt.rcParams.update({
    'font.size': 12,
    'axes.titlesize': 14,
    'axes.labelsize': 12,
    'xtick.labelsize': 10,
    'ytick.labelsize': 10,
    'legend.fontsize': 10,
    'figure.dpi': 300,
    'savefig.dpi': 300,
    'savefig.bbox': 'tight'
})

"""# **Intra-subject P600 decoding**



"""

drive.mount('/content/drive')
BASE_DIR = '/content/drive/MyDrive/EEG_data/2405_intra-subject_decoding'

print(f"Drive mounted. Target base directory: {BASE_DIR}")
print(f"Directory exists: {os.path.exists(BASE_DIR)}")

# Data loading and verification
import os
import pandas as pd
import pickle

# defining the file paths
results_csv_path = os.path.join(BASE_DIR, 'intra-subject_results.csv')
viz_data_path = os.path.join(BASE_DIR, 'visualization_data.pkl')

# loading aggregated results
try:
    df_intra_results = pd.read_csv(results_csv_path)
    print("--- Aggregated Metrics csv ---")
    print(df_intra_results.head())
    print(f"\nCSV Columns: {df_intra_results.columns.tolist()}")
except FileNotFoundError:
    print(f"Error: Could not find {results_csv_path}")

# loading the visualization arrays for ROC and CFM
try:
    with open(viz_data_path, 'rb') as f:
        viz_data = pickle.load(f)
    print("\n--- Visualization pkl File ---")
    print(f"Primary Keys: {list(viz_data.keys())}")

    # structure of the first models
    first_model = list(viz_data.keys())[0]
    print(f"\nInspecting structure for model: '{first_model}'")
    for key, value in viz_data[first_model].items():
        if isinstance(value, list):
            print(f"  {key}: list of length {len(value)}")
        elif hasattr(value, 'shape'):
            print(f"  {key}: array of shape {value.shape}")
        else:
            print(f"  {key}: {type(value)}")
except FileNotFoundError:
    print(f"Error: Could not find {viz_data_path}")

"""## 1. Within-Sub Metric Summary Bar Chart

"""

import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns
import matplotlib.lines as mlines
import os

def plot_intra_subject_metrics(df, save_dir):
    # aggregate metrics across the sub
    agg_df = df.groupby('Model').agg(
        Mean_Accuracy=('Accuracy', lambda x: x.mean() * 100),
        Mean_STD=('STD', lambda x: x.mean() * 100),
        Pct_Significant=('p_value', lambda x: (x < 0.05).mean() * 100)
    ).reset_index() # Calculating percentage of subjects where p < 0.05 !!!!

    # sorting by accuracy
    agg_df = agg_df.sort_values(by='Mean_Accuracy', ascending=False)

    fig, ax = plt.subplots(figsize=(10, 6))

    x_pos = np.arange(len(agg_df['Model']))
    bar_width = 0.6

    # PLOTTING BARS
    bars = ax.bar(x_pos, agg_df['Mean_Accuracy'], bar_width,
                  yerr=agg_df['Mean_STD'], capsize=5,
                  color=sns.color_palette("Blues_r", len(agg_df)),
                  edgecolor='black', alpha=0.8)

    # formatting and threshold
    ax.set_ylabel('Mean Classification Accuracy (%)')
    ax.set_xlabel('Machine Learning Model')
    ax.set_title('5-fold Within-Subject Classification Performance (P600)', fontweight='bold', pad=15)
    ax.set_xticks(x_pos)
    ax.set_xticklabels(agg_df['Model'])

    # strcit 0-100 bound on y axis
    ax.set_ylim(0, 100)

    # chance level
    ax.axhline(y=50, color='red', linestyle='--', linewidth=1.5, label='Theoretical Chance (50%)')

    # annotations (Accuracy value and % Significant)
    for i, bar in enumerate(bars):
        acc_val = agg_df['Mean_Accuracy'].iloc[i]
        sig_val = agg_df['Pct_Significant'].iloc[i]

        y_text = acc_val + agg_df['Mean_STD'].iloc[i] + 2

        annotation_text = f"{acc_val:.1f}%\n({sig_val:.1f}% sig.)"
        ax.text(bar.get_x() + bar.get_width()/2, y_text,
                annotation_text, ha='center', va='bottom',
                fontsize=10, fontweight='bold', color='black')

    # LEGEND
    handles, labels = ax.get_legend_handles_labels()

    # PATCHED MARKER: Removed markeredgewidth, set moderate markersize=16, enforced black color
    sig_marker = mlines.Line2D([], [], color='none', marker=r'$\mathrm{sig.}$',
                               markersize=16, markerfacecolor='black', markeredgecolor='black', label='p<0.05')
    handles.append(sig_marker)
    labels.append('Subjects with p<0.05')

    ax.legend(handles=handles, labels=labels, loc='upper right')
    ax.grid(axis='y', linestyle='--', alpha=0.7)

    plt.tight_layout()

    # EXPORT LOGIC
    fig_path = os.path.join(save_dir, 'within-sub_class_results.png')
    fig.savefig(fig_path, dpi=300, bbox_inches='tight')
    plt.show()

    print(f"Saved: {fig_path}")

# EXECUTING THE FUNCTION
plot_intra_subject_metrics(df_intra_results, FIG_DIR)

"""## 2. Within-Subject Expertise Comparison

    Generates a grouped bar chart comparing Novice vs.
    Expert decoding accuracies. Includes scaled error bars and subgroup-specific significance percentages.




"""

import matplotlib.lines as mlines
import matplotlib.pyplot as plt
import numpy as np
import os

def plot_expertise_comparison(df, save_dir):
    # aggregate metrics by MODEL and EXPERTISE
    agg_df = df.groupby(['Model', 'Expertise']).agg(
        Mean_Accuracy=('Accuracy', lambda x: x.mean() * 100),
        Mean_STD=('STD', lambda x: x.mean() * 100),
        Pct_Significant=('p_value', lambda x: (x < 0.05).mean() * 100)
    ).reset_index()

    # model ordering
    model_order = df.groupby('Model')['Accuracy'].mean().sort_values(ascending=False).index

    # setup figure
    fig, ax = plt.subplots(figsize=(12, 7))

    x = np.arange(len(model_order))
    width = 0.35

    # COLOR-PALETTE
    # colors = {'Novice': '#74a9cf', 'Expert': '#045a8d'}
    colors = {'Novice': '#1f78b4', 'Expert': '#d62728'}

    # PLOTTING BARS
    for i, expertise in enumerate(['Novice', 'Expert']):
        exp_data = agg_df[agg_df['Expertise'] == expertise]
        exp_data = exp_data.set_index('Model').reindex(model_order).reset_index()

        # calculating offset
        offset = (i - 0.5) * width
        x_pos = x + offset

        bars = ax.bar(x_pos, exp_data['Mean_Accuracy'], width,
                      yerr=exp_data['Mean_STD'], capsize=5,
                      label=expertise, color=colors.get(expertise, 'gray'),
                      edgecolor='black', alpha=0.9)

        # annotations (Accuracy and % Significant per subgroup)
        for j, bar in enumerate(bars):
            acc_val = exp_data['Mean_Accuracy'].iloc[j]
            sig_val = exp_data['Pct_Significant'].iloc[j]
            std_val = exp_data['Mean_STD'].iloc[j]

            if np.isnan(acc_val):
                continue

            y_text = acc_val + std_val + 2
            annotation_text = f"{acc_val:.1f}%\n({sig_val:.0f}% sig.)"

            ax.text(bar.get_x() + bar.get_width()/2, y_text,
                    annotation_text, ha='center', va='bottom',
                    fontsize=9, fontweight='bold', color='black')

    # formatting and threshold
    ax.set_ylabel('Mean Classification Accuracy (%)')
    ax.set_xlabel('Machine Learning Model')
    ax.set_title('5-fold Within-Subject Classification: Novices vs. Experts (P600)', fontweight='bold', pad=15)
    ax.set_xticks(x)
    ax.set_xticklabels(model_order)
    ax.set_ylim(0, 100)

    ax.axhline(y=50, color='red', linestyle='--', linewidth=1.5, label='Theoretical Chance (50%)')

    # LEGEND
    handles, labels = ax.get_legend_handles_labels()
    sig_marker = mlines.Line2D([], [], color='none', marker=r'$\mathrm{sig.}$',
                               markersize=22, markerfacecolor='black', label='p<0.05')
    handles.append(sig_marker)
    labels.append('Subjects with p<0.05')

    ax.legend(handles=handles, labels=labels, title='Expertise Level', loc='upper right')
    ax.grid(axis='y', linestyle='--', alpha=0.7)

    plt.tight_layout()

    # EXPORT
    fig_path = os.path.join(save_dir, 'classifier_expertise.png')
    fig.savefig(fig_path, dpi=300, bbox_inches='tight')
    plt.show()

    print(f"Saved: {fig_path}")

# EXECUTING FUNCTION
plot_expertise_comparison(df_intra_results, FIG_DIR)

"""## 3. Within-Subject Edge Case Analysis (TABLE)

    Identifies the top 3 and bottom 3 subjects by mean accuracy,
    and formats their metrics into a publication-ready pivoted table.

"""

import os
import pandas as pd
from IPython.display import display

# dir
FIG_DIR = os.path.join(BASE_DIR, 'figures')
if not os.path.exists(FIG_DIR):
    os.makedirs(FIG_DIR)
    print(f"Created directory: {FIG_DIR}")

def generate_extremes_table(df):
    # ranking subs by acc
    sub_perf = df.groupby(['Subject', 'Expertise'])['Accuracy'].mean().sort_values(ascending=False).reset_index()

    top_3 = sub_perf.head(3)['Subject'].tolist()
    bot_3 = sub_perf.tail(3)['Subject'].tolist()

    # filtering for 3 bets and 3 worst subs
    df_filtered = df[df['Subject'].isin(top_3 + bot_3)].copy()

    # assigning performance
    df_filtered['Performance_Tier'] = df_filtered['Subject'].apply(
        lambda x: 'Top 3 (Highest Decodability)' if x in top_3 else 'Bottom 3 (Lowest Decodability)'
    )

    # formatting metrics
    def format_metrics(row):
        acc = row['Accuracy'] * 100
        std = row['STD'] * 100
        p = row['p_value']
        # Format p-value strictly
        p_str = "<0.001" if p < 0.001 else f"={p:.3f}"
        return f"{acc:.1f}% ± {std:.1f} (p{p_str})"

    df_filtered['Formatted_Metrics'] = df_filtered.apply(format_metrics, axis=1)

    # TABLE OUTPUT
    clean_table = df_filtered.pivot(
        index=['Performance_Tier', 'Subject', 'Expertise'],
        columns='Model',
        values='Formatted_Metrics'
    )

    # ascending order
    clean_table = clean_table.reindex(['Top 3 (Highest Decodability)', 'Bottom 3 (Lowest Decodability)'], level=0)

    return clean_table

pd.set_option('display.max_columns', None)
pd.set_option('display.max_colwidth', None)

# EXECUTION
extremes_table = generate_extremes_table(df_intra_results)
display(extremes_table)

# EXPORT PROTOCOL
csv_path = os.path.join(FIG_DIR, 'Table_Extreme_Subjects.csv')
html_path = os.path.join(FIG_DIR, 'Table_Extreme_Subjects.html')
excel_path = os.path.join(FIG_DIR, 'Table_Extreme_Subjects.xlsx')

# multiple formats
extremes_table.to_csv(csv_path)
extremes_table.to_html(html_path)
extremes_table.to_excel(excel_path)

print(f"\n--- TABLE SUCCESSFULLY EXPORTED ---")
print(f"CSV saved to: {csv_path}")
print(f"HTML saved to: {html_path}")
print(f"Excel saved to: {excel_path}")

"""## 4. Confusion-Matrix

    Extracts, sums, and normalizes confusion matrices across all subjects.
    Plots a 2x2 grid for the 4 intra-subject models.
    
"""

#aggregate and plot individual Normalized Confusion Matrices
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import os

def plot_individual_confusion_matrices(viz_dict, save_dir):
    # dicts to hold the cm
    cm_aggregate = {}
    subjects_per_model = {}

    # iterating through the dict
    for sub, sub_data in viz_dict.items():
        models_dict = sub_data.get('models', {})
        for model_name, metrics in models_dict.items():
            cm = metrics.get('confusion_matrix')

            if cm is not None:
                cm = np.array(cm)
                if model_name not in cm_aggregate:
                    cm_aggregate[model_name] = np.zeros_like(cm, dtype=float)
                    subjects_per_model[model_name] = 0
                cm_aggregate[model_name] += cm
                subjects_per_model[model_name] += 1

    # CLASS LABELS
    class_labels = ['Invalid Code', 'Valid Code']

    # generate each cm seperately
    for model_name, raw_cm in cm_aggregate.items():

        # SETUP OF THE FIGURE
        fig, ax = plt.subplots(figsize=(6, 5))

        # plotting the heatmap (raw counts, specific scale, unbolded text)
        sns.heatmap(raw_cm, annot=True, fmt='.0f', cmap='Blues', cbar=True,
                    xticklabels=class_labels, yticklabels=class_labels,
                    ax=ax, annot_kws={'size': 14},
                    vmin=800, vmax=1100,
                    cbar_kws={'ticks': [800, 850, 900, 950, 1000, 1050, 1100]})

        # formatting (only model name and n, no main suptitle)
        ax.set_title(f"{model_name} (n={subjects_per_model[model_name]})", fontsize=14, pad=10)
        ax.set_ylabel('True Label')
        ax.set_xlabel('Predicted Label')

        # adding border for academic styling
        for _, spine in ax.spines.items():
            spine.set_visible(True)
            spine.set_color('black')
            spine.set_linewidth(1)

        plt.tight_layout()

        # saving the figure
        fig_path = os.path.join(save_dir, f"CM_Intra_{model_name}.png")
        fig.savefig(fig_path, dpi=300, bbox_inches='tight')
        plt.show()

        print(f"Saved: {fig_path}")

# EXECUTING FUNCTION
plot_individual_confusion_matrices(viz_data, BASE_DIR)